defmodule ExSportsdataio.NBA.Playerseason do
  @moduledoc """
  Struct for NBA Playerseason data.
  """

  @type t :: %__MODULE__{
          statid: integer(),
          teamid: integer(),
          playerid: integer(),
          seasontype: integer(),
          season: integer(),
          name: String.t(),
          team: String.t(),
          position: String.t(),
          started: integer() | nil,
          globalteamid: integer() | nil,
          updated: any(),
          games: integer() | nil,
          fantasypoints: float() | nil,
          minutes: integer() | nil,
          seconds: integer() | nil,
          fieldgoalsmade: integer() | nil,
          fieldgoalsattempted: integer() | nil,
          fieldgoalspercentage: float() | nil,
          effectivefieldgoalspercentage: float() | nil,
          twopointersmade: integer() | nil,
          twopointersattempted: integer() | nil,
          twopointerspercentage: float() | nil,
          threepointersmade: integer() | nil,
          threepointersattempted: integer() | nil,
          threepointerspercentage: float() | nil,
          freethrowsmade: integer() | nil,
          freethrowsattempted: integer() | nil,
          freethrowspercentage: float() | nil,
          offensiverebounds: integer() | nil,
          defensiverebounds: integer() | nil,
          rebounds: integer() | nil,
          offensivereboundspercentage: any(),
          defensivereboundspercentage: any(),
          totalreboundspercentage: any(),
          assists: any(),
          steals: any(),
          blockedshots: any(),
          turnovers: any(),
          personalfouls: any(),
          points: any(),
          trueshootingattempts: any(),
          trueshootingpercentage: any(),
          playerefficiencyrating: any(),
          assistspercentage: any(),
          stealspercentage: any(),
          blockspercentage: any(),
          turnoverspercentage: any(),
          usageratepercentage: any(),
          fantasypointsfanduel: any(),
          fantasypointsdraftkings: any(),
          fantasypointsyahoo: any(),
          plusminus: any(),
          doubledoubles: any(),
          tripledoubles: any(),
          fantasypointsfantasydraft: any(),
          isclosed: boolean(),
          lineupconfirmed: boolean(),
          lineupstatus: String.t()
        }

  @derive [Poison.Encoder]
  defstruct [
    :statid,
    :teamid,
    :playerid,
    :seasontype,
    :season,
    :name,
    :team,
    :position,
    :started,
    :globalteamid,
    :updated,
    :games,
    :fantasypoints,
    :minutes,
    :seconds,
    :fieldgoalsmade,
    :fieldgoalsattempted,
    :fieldgoalspercentage,
    :effectivefieldgoalspercentage,
    :twopointersmade,
    :twopointersattempted,
    :twopointerspercentage,
    :threepointersmade,
    :threepointersattempted,
    :threepointerspercentage,
    :freethrowsmade,
    :freethrowsattempted,
    :freethrowspercentage,
    :offensiverebounds,
    :defensiverebounds,
    :rebounds,
    :offensivereboundspercentage,
    :defensivereboundspercentage,
    :totalreboundspercentage,
    :assists,
    :steals,
    :blockedshots,
    :turnovers,
    :personalfouls,
    :points,
    :trueshootingattempts,
    :trueshootingpercentage,
    :playerefficiencyrating,
    :assistspercentage,
    :stealspercentage,
    :blockspercentage,
    :turnoverspercentage,
    :usageratepercentage,
    :fantasypointsfanduel,
    :fantasypointsdraftkings,
    :fantasypointsyahoo,
    :plusminus,
    :doubledoubles,
    :tripledoubles,
    :fantasypointsfantasydraft,
    :isclosed,
    :lineupconfirmed,
    :lineupstatus
  ]
end
