defmodule ExSportsdataio.MLB.Player.GameStats do
  @moduledoc """
  Struct for MLB PlayerGame data.
  """
  alias ExSportsdataio.Client

  @type t :: %__MODULE__{
          stat_id: integer(),
          team_id: integer() | nil,
          player_id: integer() | nil,
          season_type: integer() | nil,
          season: integer() | nil,
          name: String.t() | nil,
          team: String.t() | nil,
          position: String.t() | nil,
          position_category: String.t() | nil,
          started: integer() | nil,
          batting_order: integer() | nil,
          fan_duel_salary: integer() | nil,
          draft_kings_salary: integer() | nil,
          fantasy_data_salary: integer() | nil,
          yahoo_salary: integer() | nil,
          injury_status: String.t() | nil,
          injury_body_part: String.t() | nil,
          injury_start_date: String.t() | nil,
          injury_notes: String.t() | nil,
          fan_duel_position: String.t() | nil,
          draft_kings_position: String.t() | nil,
          yahoo_position: String.t() | nil,
          opponent_rank: integer() | nil,
          opponent_position_rank: integer() | nil,
          global_team_id: integer(),
          fantasy_draft_salary: integer() | nil,
          fantasy_draft_position: String.t() | nil,
          game_id: integer() | nil,
          opponent_id: integer() | nil,
          opponent: String.t() | nil,
          day: String.t() | nil,
          date_time: String.t() | nil,
          home_or_away: String.t() | nil,
          is_game_over: boolean(),
          global_game_id: integer() | nil,
          global_opponent_id: integer() | nil,
          updated: String.t() | nil,
          games: integer() | nil,
          fantasy_points: float() | nil,
          at_bats: float() | nil,
          runs: float() | nil,
          hits: float() | nil,
          singles: float() | nil,
          doubles: float() | nil,
          triples: float() | nil,
          home_runs: float() | nil,
          runs_batted_in: float() | nil,
          batting_average: float() | nil,
          outs: float() | nil,
          strikeouts: float() | nil,
          walks: float() | nil,
          hit_by_pitch: float() | nil,
          sacrifices: float() | nil,
          sacrifice_flies: float() | nil,
          ground_into_double_play: float() | nil,
          stolen_bases: float() | nil,
          caught_stealing: float() | nil,
          pitches_seen: float() | nil,
          on_base_percentage: float() | nil,
          slugging_percentage: float() | nil,
          on_base_plus_slugging: float() | nil,
          errors: float() | nil,
          wins: float() | nil,
          losses: float() | nil,
          saves: float() | nil,
          innings_pitched_decimal: float() | nil,
          total_outs_pitched: float() | nil,
          innings_pitched_full: float() | nil,
          innings_pitched_outs: float() | nil,
          earned_run_average: float() | nil,
          pitching_hits: float() | nil,
          pitching_runs: float() | nil,
          pitching_earned_runs: float() | nil,
          pitching_walks: float() | nil,
          pitching_strikeouts: float() | nil,
          pitching_home_runs: float() | nil,
          pitches_thrown: float() | nil,
          pitches_thrown_strikes: float() | nil,
          walks_hits_per_innings_pitched: float() | nil,
          pitching_batting_average_against: float() | nil,
          grand_slams: float() | nil,
          fantasy_points_fan_duel: float() | nil,
          fantasy_points_draft_kings: float() | nil,
          fantasy_points_yahoo: float() | nil,
          plate_appearances: float() | nil,
          total_bases: float() | nil,
          fly_outs: float() | nil,
          ground_outs: float() | nil,
          line_outs: float() | nil,
          pop_outs: float() | nil,
          intentional_walks: float() | nil,
          reached_on_error: float() | nil,
          balls_in_play: float() | nil,
          batting_average_on_balls_in_play: float() | nil,
          weighted_on_base_percentage: float() | nil,
          pitching_singles: float() | nil,
          pitching_doubles: float() | nil,
          pitching_triples: float() | nil,
          pitching_grand_slams: float() | nil,
          pitching_hit_by_pitch: float() | nil,
          pitching_sacrifices: float() | nil,
          pitching_sacrifice_flies: float() | nil,
          pitching_ground_into_double_play: float() | nil,
          pitching_complete_games: float() | nil,
          pitching_shut_outs: float() | nil,
          pitching_no_hitters: float() | nil,
          pitching_perfect_games: float() | nil,
          pitching_plate_appearances: float() | nil,
          pitching_total_bases: float() | nil,
          pitching_fly_outs: float() | nil,
          pitching_ground_outs: float() | nil,
          pitching_line_outs: float() | nil,
          pitching_pop_outs: float() | nil,
          pitching_intentional_walks: float() | nil,
          pitching_reached_on_error: float() | nil,
          pitching_catchers_interference: float() | nil,
          pitching_balls_in_play: float() | nil,
          pitching_on_base_percentage: float() | nil,
          pitching_slugging_percentage: float() | nil,
          pitching_on_base_plus_slugging: float() | nil,
          pitching_strikeouts_per_nine_innings: float() | nil,
          pitching_walks_per_nine_innings: float() | nil,
          pitching_batting_average_on_balls_in_play: float() | nil,
          pitching_weighted_on_base_percentage: float() | nil,
          double_plays: float() | nil,
          pitching_double_plays: float() | nil,
          batting_order_confirmed: boolean() | nil,
          isolated_power: float() | nil,
          fielding_independent_pitching: float() | nil,
          pitching_quality_starts: float() | nil,
          pitching_inning_started: integer() | nil,
          left_on_base: float() | nil,
          pitching_holds: float() | nil,
          pitching_blown_saves: float() | nil,
          substitute_batting_order: integer() | nil,
          substitute_batting_order_sequence: integer() | nil,
          fantasy_points_fantasy_draft: float() | nil,
          fantasy_points_batting: float() | nil,
          fantasy_points_pitching: float() | nil
        }

  defstruct [
    :stat_id,
    :team_id,
    :player_id,
    :season_type,
    :season,
    :name,
    :team,
    :position,
    :position_category,
    :started,
    :batting_order,
    :fan_duel_salary,
    :draft_kings_salary,
    :fantasy_data_salary,
    :yahoo_salary,
    :injury_status,
    :injury_body_part,
    :injury_start_date,
    :injury_notes,
    :fan_duel_position,
    :draft_kings_position,
    :yahoo_position,
    :opponent_rank,
    :opponent_position_rank,
    :global_team_id,
    :fantasy_draft_salary,
    :fantasy_draft_position,
    :game_id,
    :opponent_id,
    :opponent,
    :day,
    :date_time,
    :home_or_away,
    :is_game_over,
    :global_game_id,
    :global_opponent_id,
    :updated,
    :games,
    :fantasy_points,
    :at_bats,
    :runs,
    :hits,
    :singles,
    :doubles,
    :triples,
    :home_runs,
    :runs_batted_in,
    :batting_average,
    :outs,
    :strikeouts,
    :walks,
    :hit_by_pitch,
    :sacrifices,
    :sacrifice_flies,
    :ground_into_double_play,
    :stolen_bases,
    :caught_stealing,
    :pitches_seen,
    :on_base_percentage,
    :slugging_percentage,
    :on_base_plus_slugging,
    :errors,
    :wins,
    :losses,
    :saves,
    :innings_pitched_decimal,
    :total_outs_pitched,
    :innings_pitched_full,
    :innings_pitched_outs,
    :earned_run_average,
    :pitching_hits,
    :pitching_runs,
    :pitching_earned_runs,
    :pitching_walks,
    :pitching_strikeouts,
    :pitching_home_runs,
    :pitches_thrown,
    :pitches_thrown_strikes,
    :walks_hits_per_innings_pitched,
    :pitching_batting_average_against,
    :grand_slams,
    :fantasy_points_fan_duel,
    :fantasy_points_draft_kings,
    :fantasy_points_yahoo,
    :plate_appearances,
    :total_bases,
    :fly_outs,
    :ground_outs,
    :line_outs,
    :pop_outs,
    :intentional_walks,
    :reached_on_error,
    :balls_in_play,
    :batting_average_on_balls_in_play,
    :weighted_on_base_percentage,
    :pitching_singles,
    :pitching_doubles,
    :pitching_triples,
    :pitching_grand_slams,
    :pitching_hit_by_pitch,
    :pitching_sacrifices,
    :pitching_sacrifice_flies,
    :pitching_ground_into_double_play,
    :pitching_complete_games,
    :pitching_shut_outs,
    :pitching_no_hitters,
    :pitching_perfect_games,
    :pitching_plate_appearances,
    :pitching_total_bases,
    :pitching_fly_outs,
    :pitching_ground_outs,
    :pitching_line_outs,
    :pitching_pop_outs,
    :pitching_intentional_walks,
    :pitching_reached_on_error,
    :pitching_catchers_interference,
    :pitching_balls_in_play,
    :pitching_on_base_percentage,
    :pitching_slugging_percentage,
    :pitching_on_base_plus_slugging,
    :pitching_strikeouts_per_nine_innings,
    :pitching_walks_per_nine_innings,
    :pitching_batting_average_on_balls_in_play,
    :pitching_weighted_on_base_percentage,
    :double_plays,
    :pitching_double_plays,
    :batting_order_confirmed,
    :isolated_power,
    :fielding_independent_pitching,
    :pitching_quality_starts,
    :pitching_inning_started,
    :left_on_base,
    :pitching_holds,
    :pitching_blown_saves,
    :substitute_batting_order,
    :substitute_batting_order_sequence,
    :fantasy_points_fantasy_draft,
    :fantasy_points_batting,
    :fantasy_points_pitching
  ]

  def get_player_game_stats_by_date(date) do
    Client.request(
      "/mlb/stats/json/playergamestatsbydate/:date",
      %{opts: [path_params: [date: date]]}
    )
    |> Client.handle_response(%__MODULE__{})
  end
end
