defmodule ExSportsdataio.MLB.Player do
  @moduledoc """
  Struct for MLB Player data.
  """

  @type t :: %__MODULE__{
          player_id: integer(),
          sports_data_id: String.t() | nil,
          status: String.t() | nil,
          team_id: integer() | nil,
          team: String.t() | nil,
          jersey: integer() | nil,
          position_category: String.t() | nil,
          position: String.t() | nil,
          mlbam_id: integer() | nil,
          first_name: String.t() | nil,
          last_name: String.t() | nil,
          bat_hand: String.t() | nil,
          throw_hand: String.t() | nil,
          height: integer() | nil,
          weight: integer() | nil,
          birth_date: String.t() | nil,
          birth_city: String.t() | nil,
          birth_state: String.t() | nil,
          birth_country: String.t() | nil,
          high_school: String.t() | nil,
          college: String.t() | nil,
          pro_debut: String.t() | nil,
          salary: integer() | nil,
          photo_url: String.t() | nil,
          sport_radar_player_id: String.t() | nil,
          rotoworld_player_id: integer() | nil,
          roto_wire_player_id: integer() | nil,
          fantasy_alarm_player_id: integer() | nil,
          stats_player_id: integer() | nil,
          sports_direct_player_id: integer() | nil,
          xml_team_player_id: integer() | nil,
          injury_status: String.t() | nil,
          injury_body_part: String.t() | nil,
          injury_start_date: String.t() | nil,
          injury_notes: String.t() | nil,
          fan_duel_player_id: integer() | nil,
          draft_kings_player_id: integer() | nil,
          yahoo_player_id: integer() | nil,
          upcoming_game_id: integer() | nil,
          fan_duel_name: String.t() | nil,
          draft_kings_name: String.t() | nil,
          yahoo_name: String.t() | nil,
          global_team_id: integer(),
          fantasy_draft_name: String.t() | nil,
          fantasy_draft_player_id: integer() | nil,
          experience: String.t() | nil,
          usa_today_player_id: integer() | nil,
          usa_today_headshot_url: String.t() | nil,
          usa_today_headshot_no_background_url: String.t() | nil,
          usa_today_headshot_updated: String.t() | nil,
          usa_today_headshot_no_background_updated: String.t() | nil
        }

  defstruct [
    :player_id,
    :sports_data_id,
    :status,
    :team_id,
    :team,
    :jersey,
    :position_category,
    :position,
    :mlbam_id,
    :first_name,
    :last_name,
    :bat_hand,
    :throw_hand,
    :height,
    :weight,
    :birth_date,
    :birth_city,
    :birth_state,
    :birth_country,
    :high_school,
    :college,
    :pro_debut,
    :salary,
    :photo_url,
    :sport_radar_player_id,
    :rotoworld_player_id,
    :roto_wire_player_id,
    :fantasy_alarm_player_id,
    :stats_player_id,
    :sports_direct_player_id,
    :xml_team_player_id,
    :injury_status,
    :injury_body_part,
    :injury_start_date,
    :injury_notes,
    :fan_duel_player_id,
    :draft_kings_player_id,
    :yahoo_player_id,
    :upcoming_game_id,
    :fan_duel_name,
    :draft_kings_name,
    :yahoo_name,
    :global_team_id,
    :fantasy_draft_name,
    :fantasy_draft_player_id,
    :experience,
    :usa_today_player_id,
    :usa_today_headshot_url,
    :usa_today_headshot_no_background_url,
    :usa_today_headshot_updated,
    :usa_today_headshot_no_background_updated
  ]
end
